project_id = "lxghuqiheaoinytrwhac"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.process-email-queue]
    verify_jwt = true
  [functions.check-face-duplicate]
    verify_jwt = false
