project_id = "lxghuqiheaoinytrwhac"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.process-email-queue]
    verify_jwt = true
  [functions.check-face-duplicate]
    verify_jwt = false
  [functions.verify-face-human]
    verify_jwt = false
  [functions.set-verified-avatar]
    verify_jwt = false
  [functions.vapid-public-key]
    verify_jwt = false
  [functions.send-push]
    verify_jwt = false
